# Appium 服务器配置
appium_server:
  host: localhost
  port: 4723

devices:
  # iOS 配置
  ios:
    - name: "iPhone 14"
      platformName: iOS
      deviceName: iPhone 14
      platformVersion: '16.0'
      automationName: XCUITest
      bundleId: com.apple.calculator
      noReset: true
    - name: "iPhone 13"
      platformName: iOS
      deviceName: iPhone 13
      platformVersion: '15.0'
      automationName: XCUITest
      bundleId: com.apple.calculator
      noReset: true

  # Android 配置
  android:
    - name: "Pixel 6"
      platformName: Android
      deviceName: Pixel_6_API_31
      platformVersion: '12.0'
      automationName: UiAutomator2
      appPackage: com.android.chrome  # 更新为 Chrome 浏览器
      appActivity: com.google.android.apps.chrome.Main  # 更新为 Chrome 主活动
      noReset: true
    - name: "Pixel 4"
      platformName: Android
      deviceName: Pixel_4_API_30
      platformVersion: '11.0'
      automationName: UiAutomator2
      appPackage: com.android.chrome  # 更新为 Chrome 浏览器
      appActivity: com.google.android.apps.chrome.Main  # 更新为 Chrome 主活动
      noReset: true

  # android emulator
  android emulator:
    - name: "Pixel 7"
      platformName: Android
      deviceName: emulator-5554
      platformVersion: '15.0'  # 更新为实际可用的版本
      automationName: UiAutomator2
      appPackage: com.android.chrome  # 更新为 Chrome 浏览器
      appActivity: com.google.android.apps.chrome.Main  # 更新为 Chrome 主活动
      noReset: true
    - name: "Pixel 8"
      platformName: Android
      deviceName: emulator-5556
      platformVersion: '14.0'
      automationName: UiAutomator2
      appPackage: com.android.chrome  # 更新为 Chrome 浏览器
      appActivity: com.google.android.apps.chrome.Main  # 更新为 Chrome 主活动
      noReset: true
    - name: "Pixel 6"
      platformName: Android
      deviceName: Pixel_6_API_33
      platformVersion: '15.0'  # 更新为实际可用的版本
      automationName: UiAutomator2
      appPackage: com.android.chrome  # 更新为 Chrome 浏览器
      appActivity: com.google.android.apps.chrome.Main  # 更新为 Chrome 主活动
      noReset: true

  # 鸿蒙配置
  harmony:
    - name: "Harmony Device 1"
      platformName: HarmonyOS
      deviceName: Harmony_Device_1
      platformVersion: '2.0'
      automationName: UiAutomator2
      appPackage: com.example.harmonyapp
      appActivity: .MainActivity
      noReset: true
    - name: "Harmony Device 2"
      platformName: HarmonyOS
      deviceName: Harmony_Device_2
      platformVersion: '2.0'
      automationName: UiAutomator2
      appPackage: com.example.harmonyapp
      appActivity: .MainActivity
      noReset: true

# 测试配置
test_info:
  implicit_wait: 10
  timeout: 30
  default_device: 0  # 默认使用第一个设备

# 应用功能描述
app_features:
  login:
    description: "用户登录模块"
    elements:
      - name: "用户名输入框"
        type: "input"
        id: "username_input"
        placeholder: "请输入用户名"
      - name: "密码输入框"
        type: "input"
        id: "password_input"
        placeholder: "请输入密码"
      - name: "登录按钮"
        type: "button"
        id: "login_button"
        text: "登录"
      - name: "忘记密码"
        type: "link"
        id: "forget_pwd"
        text: "忘记密码？"
    validations:
      - "用户名不能为空"
      - "密码不能为空"
      - "用户名格式错误"
      - "密码长度不足"
      
  home:
    description: "首页模块"
    elements:
      - name: "搜索框"
        type: "search"
        id: "search_input"
        placeholder: "搜索商品"
      - name: "banner轮播"
        type: "swipe"
        id: "banner_container"
      - name: "商品列表"
        type: "list"
        id: "product_list"
        child_elements:
          - name: "商品图片"
            type: "image"
            id: "product_image"
          - name: "商品名称"
            type: "text"
            id: "product_name"
          - name: "商品价格"
            type: "text"
            id: "product_price"
    gestures:
      - "下拉刷新"
      - "上拉加载"
      
  product_detail:
    description: "商品详情模块"
    elements:
      - name: "商品大图"
        type: "gallery"
        id: "product_gallery"
      - name: "商品标题"
        type: "text"
        id: "product_title"
      - name: "商品描述"
        type: "text"
        id: "product_desc"
      - name: "加入购物车"
        type: "button"
        id: "add_to_cart"
      - name: "立即购买"
        type: "button"
        id: "buy_now"
    media:
      - name: "商品视频"
        type: "video"
        id: "product_video"
      - name: "语音介绍"
        type: "audio"
        id: "product_audio"
